### ISSUE TITLE
Would you consider Readwise2Zotero-Sync...?

### ISSUE THREAD

**Issue by melat0nin** [e-alizadeh/Zotero2Readwise-Sync#2]
Hello Essi

I'm using Zotero2Readwise-Sync daily and it's been extremely helpful, thank you for all your work!

I wondered if you have considered going the other way, since Readwise now has its Reader product which is a very nice way to read articles (especially if they are non-PDF). It would be extremely cool to be able to export Reader highlights (which are Readwise highlights, of course) back into Zotero, so they appear in the Zotero interface and can be referenced in Zotero notes and e.g. when writing/citing in a word processor.

Do you think this is feasible/interesting?

Thank you again!

**Comment by e-alizadeh** [comment]
Hi @melat0nin. Sorry for the late reply. 

I haven't considered going from Readwise 2 Zotero, although I don't see why it's not possible. However, from the first look, it seems to be more challenging as you may have many Readwise highlights and it may end up creating many files in Zotero.

**Comment by folofjc** [comment]
Readwise also does not store the highlights in the pdf, and it "reflows" the pdf by default when reading. I have gone back to reading in Zotero.

**Comment by e-alizadeh** [comment]
I'm closing this I'm not planning to sync Zotero notes to Readwise.
