### ISSUE TITLE
Using `include_notes=True` in Zotero2Readwise-Sync

### ISSUE THREAD

**Issue by melat0nin** [e-alizadeh/Zotero2Readwise-Sync#4]
I wondered how to use this option when utilising Zotero2Readwise-Sync -- I have many manually-written notes in Zotero that it would be really helpful to have in Readwise, alongside the annotations (which are working great!).

**Comment by e-alizadeh** [comment]
@melat0nin sorry for the late response. You can add `--include_notes y` to the "🚀 Run Automation" step in `.github/workflows/automation.yml` file so that it becomes:

```
python script.py <readwise_token> <zotero_key> <zotero_library_id> --include_notes y
```
