### ISSUE TITLE
Annotation warning: Node.js 16 actions are deprecated.

### ISSUE THREAD

**Issue by CandiceChuDVM** [e-alizadeh/Zotero2Readwise-Sync#8]
Hi, 

Below is the complete warning sign:

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

Thanks,
Candice

**Comment by e-alizadeh** [comment]
Thanks @CandiceChuDVM for flagging this warning. It's now resolved and merged (PR https://github.com/e-alizadeh/Zotero2Readwise-Sync/pull/9). You can see the job here without that warning. https://github.com/e-alizadeh/Zotero2Readwise-Sync/actions/runs/7983585739
